[ 2024-11-29 19:22:58,267 ] 20 root - INFO - Data Ingestion has been started
[ 2024-11-29 19:22:58,267 ] 22 root - INFO - Data reading using Pandas from local file system
[ 2024-11-29 19:22:58,297 ] 24 root - INFO - Data Reading has been completed
[ 2024-11-29 19:22:58,354 ] 28 root - INFO - Raw data has been stored
[ 2024-11-29 19:22:58,357 ] 31 root - INFO - Raw data has been splitted into Train and Test set
[ 2024-11-29 19:22:58,408 ] 36 root - INFO - Data Ingestion has been completed!
[ 2024-11-29 19:22:58,409 ] 50 root - INFO - Created feature store configuration at /home/fahad/mlops/exam-3/task-1/model-training-with-modular-workflow/feature_repo/feature_store.yaml
[ 2024-11-29 19:22:58,409 ] 54 root - INFO - Configuration file content:
project: churn_prediction
provider: local
registry: data/registry.db
online_store:
  type: sqlite
offline_store:
  type: file
entity_key_serialization_version: 2
[ 2024-11-29 19:22:58,955 ] 58 root - INFO - Feature store initialized successfully
[ 2024-11-29 19:22:58,975 ] 114 root - INFO - Read train and test data completed
[ 2024-11-29 19:22:58,975 ] 115 root - INFO - Obtaining preprocessing object
[ 2024-11-29 19:22:58,975 ] 66 root - INFO - Data Transformation Started
[ 2024-11-29 19:22:58,977 ] 132 root - INFO - Applying preprocessing object on training and testing datasets.
[ 2024-11-29 19:22:59,001 ] 137 root - INFO - Starting feature store operations
[ 2024-11-29 19:22:59,026 ] 182 root - INFO - Saved feature data to feature_repo/data/train_features.parquet
[ 2024-11-29 19:22:59,029 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:22:59,034 ] 409 root - WARNING - Cannot use sqlite_vec for vector search
[ 2024-11-29 19:22:59,042 ] 229 root - INFO - Applied entity and feature view for train
[ 2024-11-29 19:22:59,042 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:22:59,048 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:22:59,048 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:05,215 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:05,387 ] 236 root - INFO - Materialized features successfully
[ 2024-11-29 19:23:05,388 ] 141 root - INFO - Pushed training data to feature store
[ 2024-11-29 19:23:05,405 ] 182 root - INFO - Saved feature data to feature_repo/data/test_features.parquet
[ 2024-11-29 19:23:05,411 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:05,420 ] 229 root - INFO - Applied entity and feature view for test
[ 2024-11-29 19:23:05,420 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:05,429 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:05,430 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:08,844 ] 920 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-11-29 19:23:10,415 ] 236 root - INFO - Materialized features successfully
[ 2024-11-29 19:23:10,416 ] 144 root - INFO - Pushed testing data to feature store
[ 2024-11-29 19:23:10,877 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0197f34fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Churn_Prediction_Pipeline
[ 2024-11-29 19:23:15,414 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0197f351e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Churn_Prediction_Pipeline
[ 2024-11-29 19:23:24,786 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0197f35390>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Churn_Prediction_Pipeline
[ 2024-11-29 19:23:40,818 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0197f35540>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Churn_Prediction_Pipeline
[ 2024-11-29 19:24:14,519 ] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0197f34370>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Modular_Workflow_Churn_Prediction_Pipeline
